Update react-json-tree dependency
bhishp/storybook-formik pull request #25
Opened 2021-06-15 01:44 UTC by markwoon

Update `react-json-tree` dependency to avoid "incorrect peer dependency" warning.

2021-09-13 12:17 UTC, bhishp requested changes
Sorry for taking time to respond to this. Before I can accept this PR I need you to also add the changes to the package-lock.json as well please. Doing an `nom install` should regenerate the lock file if you achieved this by manually editing the package.json

2021-09-13 20:46 UTC, markwoon commented
Updated package-log.json as requested.

FYI, it reported 5 high severity vulns, but I did not run `npm audit fix`.

2021-09-14 11:59 UTC, bhishp approved these changes

2021-09-14 12:00 UTC, merged

2021-09-17 09:01 UTC, bhishp commented
Deployed in `2.1.8`